### ISSUE TITLE
Cannot use YASM instance with volatile qualifier

### ISSUE THREAD

**Issue by Loic74650** [bricofoy/yasm#17]
Hello
I Love YASM. I use it in several projects. 

In one project (https://github.com/Loic74650/HenHouse), I use a low power ADAFRUIT FEATHER 32U4 AVR board which deep sleeps most of the time and regularly wakes up then uses a YASM object to move a door. It compiles and works fine. 

Now I wish to port that project to a more powerful SAMD21 board (ADAFRUIT FEATHER M0) but now the same code does not compile and gives me the following error message: 

```
HenHouseLowPower.ino: In function 'void setup()':
HenHouseLowPower:535:22: error: passing 'volatile YASM' as 'this' argument discards qualifiers [-fpermissive]
  535 |   Door.next(Door_wait);
```
Before I send you a bare bone piece of code to replicate, do you see anything obvious I should check?

Thank you

**Comment by bricofoy** [comment]
Hi Loic
Glad to know YASM is useful for you :)

Regarding the issue you are facing, I suspect this as to do with the compilation options used by this specific board. But I'm afraid the problem is far behind my knowledge of C++... :(

If you are sure you need to create the YASM object as volatile (I don't really understand why ?), maybe have a look here : https://arduino.stackexchange.com/questions/37085/compiling-errorpassing-as-this-argument

**Comment by Loic74650** [comment]
Thank you Bricofoy for the quick reply.
I am indeed not so sure I need to declare the YASM object as volatile. My understanding is that it is required for variables and functions being called inside interrupts and, perhaps after deep-sleep, when required to maintain its variables values. I was assuming YASM has some internal variables which need to remain up to date after a deep-sleep. 
Thanks for the link! I am testing the code without the volatile qualifier, will let you know how it goes

**Comment by Loic74650** [comment]
Hmm, it looks like it runs fine without the Volatile qualifier, I think you can close that (non) issue....
Thank you!

**Comment by bricofoy** [comment]
ok, thanks :)
